```yaml
services:
  - type: web
    name: telegram-card-extractor-bot
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install telethon
    startCommand: python bot.py
    envVars:
      - key: API_ID
        value: 28708347
      - key: API_HASH
        value: 4fa9a7becae9889c9052871a24facfac
      - key: BOT_TOKEN
        value: 8361809176:AAEhVdiCv6KeQpCenfbelfiEb-8W4Dwf4WY
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1
```
